### ISSUE TITLE
RuntimeError: all tensors must be on devices[0]

### ISSUE THREAD

**Issue by qkgia** [vlgiitr/Group-Level-Emotion-Recognition#6]
I got this error when running 'Model_Test_OutputSaver_TrainDataset.py'.
Traceback (most recent call last):
  File "/usr/Data/Emotion/Attention/Group-Level-Emotion-Recognition/Ensemble_Models/Model_Test_OutputSaver_TrainDataset.py", line 1418, in <module>
    model = train_model(model_ft, None, None, None, num_epochs=epochs)
  File "/usr/Data/Emotion/Attention/Group-Level-Emotion-Recognition/Ensemble_Models/Model_Test_OutputSaver_TrainDataset.py", line 1395, in train_model
    outputs, output1, output2, output3, output4, output5, output6, output7, output8, output9, output10, output11, output12, output13, output14 = model(inputs, labels, face_features_mtcnn, face_features_aligned, numberFaces, phase)  
  File "/usr/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 123, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 133, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    raise output
**RuntimeError: all tensors must be on devices[0]**

Does anyone have any idea how to solve this? 

Thank you

**Comment by qkgia** [comment]
Fixed by changing the following lines:
Line 327: model2 = nn.DataParallel(model2, device_ids=[0])
Line 1336: model_ft = nn.DataParallel(model_ft, device_ids=[0])

to
